#!/usr/bin/env bash
# Internal Files Hook Installer
# Installs the internal-files blocking hook into a target repo.
# Detects whether the repo uses the pre-commit framework or standalone hooks.
# Idempotent: safe to run multiple times.
#
# Usage:
#   bash .opencode/git-guard/install-internal-files-hook.sh <repo-path>
#   bash .opencode/git-guard/install-internal-files-hook.sh example-app

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
CANONICAL_BASH_HOOK="$WORKSPACE_ROOT/.opencode/templates/block-internal-files.sh"
CANONICAL_FRAMEWORK_HOOK="$WORKSPACE_ROOT/.opencode/hooks/block-internal-files.sh"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <repo-path>"
    echo "  repo-path can be absolute or relative to workspace root"
    exit 1
fi

REPO_INPUT="$1"

if [[ "$REPO_INPUT" != /* ]]; then
    REPO_PATH="$WORKSPACE_ROOT/$REPO_INPUT"
else
    REPO_PATH="$REPO_INPUT"
fi

REPO_PATH="$(cd "$REPO_PATH" 2>/dev/null && pwd)" || {
    echo "ERROR: Directory not found: $REPO_INPUT"
    exit 1
}

REPO_NAME="$(basename "$REPO_PATH")"
GIT_DIR="$REPO_PATH/.git"
HOOK_TARGET="$GIT_DIR/hooks/pre-commit"
PRECOMMIT_CONFIG="$REPO_PATH/.pre-commit-config.yaml"
REPO_HOOK_DIR="$REPO_PATH/.opencode/hooks"

# Validate .git directory
if [ ! -d "$GIT_DIR" ]; then
    echo "SKIP: $REPO_NAME — no .git directory"
    exit 0
fi

# Validate canonical framework hook exists (needed for both modes)
if [ ! -f "$CANONICAL_FRAMEWORK_HOOK" ]; then
    echo "ERROR: Canonical framework hook not found at $CANONICAL_FRAMEWORK_HOOK"
    exit 1
fi

# Determine which installation mode to use
if [ -f "$PRECOMMIT_CONFIG" ]; then
    # Mode 1: pre-commit framework — add the local hook entry
    echo "INSTALL: $REPO_NAME — pre-commit framework detected"

    # Check if the hook is already in the config
    if grep -q "block-internal-files" "$PRECOMMIT_CONFIG" 2>/dev/null; then
        echo "OK: $REPO_NAME — block-internal-files hook already in .pre-commit-config.yaml"

        # Ensure the symlink exists even if the config entry is present
        if [ ! -L "$REPO_HOOK_DIR/block-internal-files.sh" ] && [ ! -f "$REPO_HOOK_DIR/block-internal-files.sh" ]; then
            echo "  FIXING: Creating symlink for repo-local access to canonical hook"
            mkdir -p "$REPO_HOOK_DIR"
            REL_CANONICAL="../../../.opencode/hooks/block-internal-files.sh"
            ln -sf "$REL_CANONICAL" "$REPO_HOOK_DIR/block-internal-files.sh"
            echo "  Symlink created: $REPO_HOOK_DIR/block-internal-files.sh -> $REL_CANONICAL"
        fi

        # Reinstall pre-commit hook
        (cd "$REPO_PATH" && pre-commit install 2>/dev/null) || {
            echo "WARN: $REPO_NAME — pre-commit install failed (may already be installed)"
        }

        exit 0
    fi

    # Create repo-local symlink so pre-commit can find the script
    mkdir -p "$REPO_HOOK_DIR"
    # Use relative path: repo/.opencode/hooks/ -> ../../../.opencode/hooks/
    REL_CANONICAL="../../../.opencode/hooks/block-internal-files.sh"
    ln -sf "$REL_CANONICAL" "$REPO_HOOK_DIR/block-internal-files.sh"
    echo "  Symlink: $REPO_HOOK_DIR/block-internal-files.sh -> $REL_CANONICAL"

    # Append the hook config to the pre-commit config
    echo "" >> "$PRECOMMIT_CONFIG"
    echo "# Internal files blocker — workspace canonical (v4.3)" >> "$PRECOMMIT_CONFIG"
    echo "  - repo: local" >> "$PRECOMMIT_CONFIG"
    echo "    hooks:" >> "$PRECOMMIT_CONFIG"
    echo "      - id: block-internal-files" >> "$PRECOMMIT_CONFIG"
    echo "        name: block internal working files" >> "$PRECOMMIT_CONFIG"
    echo "        description: Prevents sprint notes, AI scratch files, and other internal docs from being committed." >> "$PRECOMMIT_CONFIG"
    echo "        entry: bash .opencode/hooks/block-internal-files.sh" >> "$PRECOMMIT_CONFIG"
    echo "        language: system" >> "$PRECOMMIT_CONFIG"
    echo "        types: [text]" >> "$PRECOMMIT_CONFIG"
    echo "        pass_filenames: true" >> "$PRECOMMIT_CONFIG"

    # Reinstall pre-commit hook to pick up new config
    (cd "$REPO_PATH" && pre-commit install 2>/dev/null) || {
        echo "WARN: $REPO_NAME — pre-commit not installed. Hook config added but not activated."
        echo "      Run 'pipx install pre-commit' then 'pre-commit install' in the repo."
        exit 0
    }

    echo "DONE: $REPO_NAME — internal-files hook installed via pre-commit framework"
else
    # Mode 2: standalone bash hook
    echo "INSTALL: $REPO_NAME — standalone hook mode"

    if [ ! -f "$CANONICAL_BASH_HOOK" ]; then
        echo "ERROR: Canonical bash hook not found at $CANONICAL_BASH_HOOK"
        exit 1
    fi

    # Check if existing pre-commit hook is from pre-commit framework
    if [ -f "$HOOK_TARGET" ]; then
        if grep -q "File generated by pre-commit" "$HOOK_TARGET" 2>/dev/null; then
            echo "WARN: $REPO_NAME — existing hook uses pre-commit framework"
            echo "      Cannot install standalone hook — add .pre-commit-config.yaml entry instead"
            echo "      See: .opencode/templates/pre-commit-internal-files.yaml"
            exit 1
        else
            echo "UPDATE: $REPO_NAME — existing standalone hook found, replacing with canonical version"
        fi
    else
        echo "INSTALL: $REPO_NAME — no pre-commit hook found"
    fi

    cp "$CANONICAL_BASH_HOOK" "$HOOK_TARGET"
    chmod +x "$HOOK_TARGET"

    if diff -q "$CANONICAL_BASH_HOOK" "$HOOK_TARGET" >/dev/null 2>&1; then
        echo "DONE: $REPO_NAME — internal-files hook installed (standalone)"
        exit 0
    else
        echo "ERROR: $REPO_NAME — hook installation verification failed"
        exit 1
    fi
fi
