#!/usr/bin/env bash
# evidence-freshness-report.sh — v4.43 Evidence Freshness Report
#
# Generates a report on manual branch protection evidence freshness.
# Shows evidence age, freshness status, and renewal actions per repo.
#
# Usage:
#   bash evidence-freshness-report.sh [--output-dir <path>]
#
# Output:
#   reports/evidence-freshness.md
#   reports/evidence-freshness.json

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
EVIDENCE_FILE="$WORKSPACE_ROOT/.opencode/config/branch-protection-evidence.yaml"
OUTPUT_DIR="$WORKSPACE_ROOT/reports"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

WARNING_DAYS=60
EXPIRY_DAYS=90
CRITICAL_EXPIRY_DAYS=120

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    *) shift ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

echo "[evidence-freshness] Generating freshness report..."

CURRENT_DATE=$(date +%Y%m%d)

# ─── Initialize JSON ────────────────────────────────────────────────────
JSON_REPOS="[]"

# ─── Markdown header ────────────────────────────────────────────────────
MD_BODY=""

# ─── Get repo names ─────────────────────────────────────────────────────
REPO_NAMES=$(awk '/^  - name:/ {print $3}' "$EVIDENCE_FILE")

while IFS= read -r REPO_NAME; do
  [[ -z "$REPO_NAME" ]] && continue

  EVIDENCE_STATUS=$(awk "/^  - name: $REPO_NAME\$/{found=1; next} /^  - name:/{found=0} found && /evidence_status:/{print \$2; exit}" "$EVIDENCE_FILE")
  RECORDED_AT=$(awk "/^  - name: $REPO_NAME\$/{found=1; next} /^  - name:/{found=0} found && /recorded_at:/{gsub(/\"/,\"\"); print \$2; exit}" "$EVIDENCE_FILE")

  EVIDENCE_AGE="unknown"
  FRESHNESS_STATUS="unknown"
  DAYS_UNTIL_EXPIRY="unknown"
  OWNER_ACTION="No action needed"

  if [[ "$EVIDENCE_STATUS" == "none" || -z "$EVIDENCE_STATUS" ]]; then
    FRESHNESS_STATUS="no_evidence"
    OWNER_ACTION="Record branch protection evidence"
  elif [[ -z "$RECORDED_AT" || "$RECORDED_AT" == "" ]]; then
    FRESHNESS_STATUS="missing_timestamp"
    OWNER_ACTION="Add recorded_at timestamp to evidence"
  else
    EVIDENCE_DATE=$(echo "$RECORDED_AT" | tr -d '-' | cut -dT -f1)
    if [[ -n "$EVIDENCE_DATE" && "$EVIDENCE_DATE" =~ ^[0-9]+$ ]]; then
      AGE_DAYS=$(( (CURRENT_DATE - EVIDENCE_DATE) ))
      EVIDENCE_AGE="${AGE_DAYS} days"

      if [[ $AGE_DAYS -lt 0 ]]; then
        FRESHNESS_STATUS="future_timestamp"
        OWNER_ACTION="Fix recorded_at — timestamp is in the future"
      elif [[ $AGE_DAYS -lt $WARNING_DAYS ]]; then
        FRESHNESS_STATUS="fresh"
        DAYS_UNTIL_EXPIRY=$((EXPIRY_DAYS - AGE_DAYS))
        OWNER_ACTION="No action needed — evidence is fresh"
      elif [[ $AGE_DAYS -lt $EXPIRY_DAYS ]]; then
        FRESHNESS_STATUS="expiring_soon"
        DAYS_UNTIL_EXPIRY=$((EXPIRY_DAYS - AGE_DAYS))
        OWNER_ACTION="⚠️ Refresh evidence soon — expires in $DAYS_UNTIL_EXPIRY days"
      elif [[ $AGE_DAYS -lt $CRITICAL_EXPIRY_DAYS ]]; then
        FRESHNESS_STATUS="stale"
        DAYS_UNTIL_EXPIRY=0
        OWNER_ACTION="🚫 Refresh evidence — expired $((AGE_DAYS - EXPIRY_DAYS)) days ago"
      else
        FRESHNESS_STATUS="critically_stale"
        DAYS_UNTIL_EXPIRY=0
        OWNER_ACTION="🚫 URGENT: Refresh evidence — expired $((AGE_DAYS - EXPIRY_DAYS)) days ago (critical at $CRITICAL_EXPIRY_DAYS days)"
      fi
    fi
  fi

  # ─── Markdown ────────────────────────────────────────────────────────
  MD_BODY+="### $REPO_NAME\n\n"
  MD_BODY+="| Field | Value |\n"
  MD_BODY+="|-------|-------|\n"
  MD_BODY+="| Evidence Status | $EVIDENCE_STATUS |\n"
  MD_BODY+="| Recorded At | ${RECORDED_AT:-missing} |\n"
  MD_BODY+="| Evidence Age | $EVIDENCE_AGE |\n"
  MD_BODY+="| Freshness | $FRESHNESS_STATUS |\n"
  MD_BODY+="| Days Until Expiry | $DAYS_UNTIL_EXPIRY |\n"
  MD_BODY+="| Owner Action | $OWNER_ACTION |\n\n"

  # ─── JSON ────────────────────────────────────────────────────────────
  JSON_REPOS=$(echo "$JSON_REPOS" | jq ". + [{\"name\":\"$REPO_NAME\",\"evidence_status\":\"$EVIDENCE_STATUS\",\"recorded_at\":\"${RECORDED_AT:-missing}\",\"evidence_age\":\"$EVIDENCE_AGE\",\"freshness\":\"$FRESHNESS_STATUS\",\"days_until_expiry\":\"$DAYS_UNTIL_EXPIRY\",\"owner_action\":\"$OWNER_ACTION\"}]")

done <<< "$REPO_NAMES"

# ─── Write markdown ────────────────────────────────────────────────────
MD_FILE="$OUTPUT_DIR/evidence-freshness.md"
{
  echo "<!-- evidence-freshness -->"
  echo "# 🕐 Evidence Freshness Report"
  echo ""
  echo "**Generated:** $TIMESTAMP"
  echo "**Thresholds:** Warning at $WARNING_DAYS days, Expiry at $EXPIRY_DAYS days, Critical at $CRITICAL_EXPIRY_DAYS days"
  echo ""
  echo "---"
  echo ""
  echo -e "$MD_BODY"
  echo "---"
  echo "*Generated by v4.43 Evidence Freshness Report*"
} > "$MD_FILE"

# ─── Write JSON ────────────────────────────────────────────────────────
JSON_FILE="$OUTPUT_DIR/evidence-freshness.json"
cat > "$JSON_FILE" << ENDJSON
{
  "generated": "$TIMESTAMP",
  "thresholds": {
    "warning_days": $WARNING_DAYS,
    "expiry_days": $EXPIRY_DAYS,
    "critical_expiry_days": $CRITICAL_EXPIRY_DAYS
  },
  "repos": $JSON_REPOS
}
ENDJSON

if command -v jq &> /dev/null; then
  jq '.' "$JSON_FILE" > "${JSON_FILE}.tmp" && mv "${JSON_FILE}.tmp" "$JSON_FILE"
fi

echo "[evidence-freshness] ✅ Report generated:"
echo "  Markdown: $MD_FILE"
echo "  JSON: $JSON_FILE"
